repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: python
        require_serial: true
        entry: bash -c 'isort "$@"; git add -u' --
      - id: format
        name: format
        language: python
        require_serial: true
        entry: bash -c 'black "$@"; git add -u' --
