---
name: CI
on:  # yamllint disable-line rule:truthy
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  statics:
    name: Static checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install '.[dev]'
      - run: pre-commit install
      - run: pre-commit run --all-files
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install '.[dev]'
      - run: pytest tests
